(in-package cl-user)

;;;
;;;--------------------------------------------
;;;  Automatically Generated nRQL Symbol List  
;;;          Version: 1.9.2  
;;;--------------------------------------------
;;;

(defpackage nrql-symbols
                 (:export #:query
                          #:with-nrql-standard-settings
                          #:racer-retrieve-individual-filled-roles
                          #:racer-retrieve-individual-fillers
                          #:racer-retrieve-related-individuals
                          #:xml-output
                          #:xml-input
                          #:lisp-to-xml
                          #:xml-to-lisp
                          #:nrql-equal-role
                          #:all-types
                          #:types
                          #:instantiators
                          #:all-instantiators
                          #:all-types-flat
                          #:all-instantiators-flat
                          #:types-flat
                          #:instantiators-flat
                          #:direct-types
                          #:most-specific-types
                          #:most-specific-instantiators
                          #:direct-instantiators
                          #:direct-types-flat
                          #:most-specific-types-flat
                          #:most-specific-instantiators-flat
                          #:direct-instantiators-flat
                          #:describe
                          #:individual-synonyms
                          #:bind-individual
                          #:inv
                          #:not
                          #:neg
                          #:and
                          #:or
                          #:satisfies
                          #:top
                          #:bottom
                          #:true-query
                          #:false-query
                          #:constraint
                          #:has-known-successor
                          #:substitute
                          #:insert
                          #:same-as
                          #:equal
                          #:=
                          #:intersection
                          #:union
                          #:cap
                          #:cup
                          #:lambda
                          #:told-value
                          #:told-values
                          #:told-value-if-exists
                          #:told-values-if-exists
                          #:datatype-filler
                          #:datatype-fillers
                          #:annotation-datatype-filler
                          #:annotation-datatype-fillers
                          #:unknown-operator
                          #:bindings-from
                          #:no-told-value
                          #:no-known-cd-objects
                          #:project
                          #:project-to
                          #:pi
                          #:real-top
                          #:real-bottom
                          #:store-substrate-for-current-abox
                          #:restore-all-substrates
                          #:restore-substrate
                          #:store-all-substrates
                          #:store-substrate-for-abox
                          #:get-nrql-version
                          #:del-rcc-edge1
                          #:del-rcc-node1
                          #:rcc-edge-label1
                          #:rcc-node-label1
                          #:rcc-edge1
                          #:rcc-node1
                          #:rcc-related1
                          #:rcc-instance1
                          #:rcc-consistent-p
                          #:create-rcc-edge
                          #:create-rcc-node
                          #:set-rcc-box
                          #:set-mirror-data-box
                          #:description-implies-p
                          #:set-data-box
                          #:get-data-edge-label
                          #:get-data-node-label
                          #:delete-data-edge
                          #:delete-data-node
                          #:create-data-edge
                          #:create-data-node
                          #:get-substrate-edge-assertions
                          #:get-substrate-edges
                          #:get-substrate-node-assertions
                          #:get-substrate-nodes
                          #:get-process-pool-size
                          #:get-maximum-size-of-process-pool
                          #:get-initial-size-of-process-pool
                          #:set-maximum-size-of-process-pool
                          #:set-initial-size-of-process-pool
                          #:set-rewrite-defined-concepts
                          #:set-nrql-mode
                          #:show-current-qbox
                          #:get-abox-of-current-qbox
                          #:disable-query-realization
                          #:enable-query-realization
                          #:optimizer-dont-use-cardinality-heuristics
                          #:optimizer-use-cardinality-heuristics
                          #:disable-query-optimization
                          #:enable-query-optimization
                          #:disable-query-repository
                          #:enable-query-repository
                          #:dont-report-tautological-queries
                          #:report-tautological-queries
                          #:dont-report-inconsistent-queries
                          #:report-inconsistent-queries
                          #:describe-query-processing-mode
                          #:describe-current-substrate
                          #:include-permutations
                          #:exclude-permutations
                          #:dont-add-rule-consequences-automatically
                          #:add-rule-consequences-automatically
                          #:process-set-at-a-time
                          #:process-tuple-at-a-time
                          #:get-max-no-of-tuples-bound
                          #:set-max-no-of-tuples-bound
                          #:dont-check-abox-consistency-before-querying
                          #:check-abox-consistency-before-querying
                          #:enable-lazy-tuple-computation
                          #:enable-eager-tuple-computation
                          #:restore-standard-settings
                          #:dont-add-role-assertions-for-datatype-properties
                          #:add-role-assertions-for-datatype-properties
                          #:disable-told-information-querying
                          #:enable-told-information-querying
                          #:disable-nrql-warnings
                          #:enable-nrql-warnings
                          #:disable-kb-has-changed-warning-tokens
                          #:enable-kb-has-changed-warning-tokens
                          #:disable-phase-two-starts-warning-tokens
                          #:enable-phase-two-starts-warning-tokens
                          #:disable-two-phase-query-processing-mode
                          #:enable-two-phase-query-processing-mode
                          #:disable-abox-mirroring
                          #:enable-very-smart-abox-mirroring
                          #:enable-smart-abox-mirroring
                          #:enable-abox-mirroring
                          #:disable-sql-data-substrate-mirroring
                          #:enable-sql-data-substrate-mirroring
                          #:use-$?-prefix-for-una-variables
                          #:use-?-prefix-for-una-variables
                          #:dont-use-individual-synonym-equivalence-classes
                          #:use-individual-synonym-equivalence-classes
                          #:disable-data-substrate-mirroring
                          #:enable-data-substrate-mirroring
                          #:wait-for-rules-to-terminate
                          #:wait-for-queries-to-terminate
                          #:describe-all-rules
                          #:describe-all-queries
                          #:get-all-answers
                          #:get-answer-size
                          #:run-all-rules
                          #:reexecute-all-rules
                          #:execute-all-rules
                          #:run-all-queries
                          #:reexecute-all-queries
                          #:execute-all-queries
                          #:abort-all-rules
                          #:abort-all-queries
                          #:terminated-rules
                          #:inactive-rules
                          #:processed-rules
                          #:terminated-queries
                          #:inactive-queries
                          #:processed-queries
                          #:waiting-expensive-rules
                          #:waiting-cheap-rules
                          #:waiting-rules
                          #:waiting-expensive-queries
                          #:waiting-cheap-queries
                          #:waiting-queries
                          #:running-expensive-rules
                          #:running-cheap-rules
                          #:running-rules
                          #:running-expensive-queries
                          #:running-cheap-queries
                          #:running-queries
                          #:active-expensive-rules
                          #:active-cheap-rules
                          #:active-rules
                          #:active-expensive-queries
                          #:active-cheap-queries
                          #:active-queries
                          #:prepared-rules
                          #:ready-rules
                          #:prepared-queries
                          #:ready-queries
                          #:expensive-rules
                          #:cheap-rules
                          #:inaccurate-rules
                          #:accurate-rules
                          #:all-rules
                          #:expensive-queries
                          #:cheap-queries
                          #:inaccurate-queries
                          #:accurate-queries
                          #:all-queries
                          #:describe-all-definitions
                          #:describe-definition
                          #:delete-all-definitions
                          #:undefine-query
                          #:define-and-prepare-query
                          #:define-and-execute-query
                          #:define-query
                          #:racer-prepare-tbox-query
                          #:racer-answer-tbox-query1
                          #:racer-answer-tbox-query
                          #:racer-prepare-rule
                          #:racer-apply-rule
                          #:prepare-nrql-engine
                          #:racer-prepare-query
                          #:racer-answer-query-under-premise
                          #:racer-answer-query1
                          #:racer-answer-query
                          #:full-reset
                          #:reset-nrql-engine
                          #:reset-all-substrates
                          #:delete-all-rules
                          #:delete-all-queries
                          #:describe-rule
                          #:describe-query
                          #:get-dag-of-qbox-for-abox
                          #:show-qbox-for-abox
                          #:get-nodes-in-qbox-for-abox
                          #:get-nodes-in-current-qbox
                          #:get-dag-of-current-qbox
                          #:query-equivalents
                          #:query-descendants
                          #:query-children
                          #:query-ancestors
                          #:query-parents
                          #:query-equivalent-p
                          #:query-entails-p
                          #:classify-query
                          #:query-tautological-p
                          #:query-inconsistent-p
                          #:query-consistent-p
                          #:abort-rule
                          #:abort-query
                          #:original-rule-body
                          #:original-query-body
                          #:rule-body
                          #:query-body
                          #:original-rule-head
                          #:original-query-head
                          #:rule-head
                          #:query-head
                          #:rule-accurate-p
                          #:query-accurate-p
                          #:get-answer
                          #:get-all-remaining-sets-of-rule-consequences
                          #:get-all-remaining-tuples
                          #:get-next-n-remaining-sets-of-rule-consequences
                          #:get-next-n-remaining-tuples
                          #:describe-rule-status
                          #:describe-query-status
                          #:rule-inactive-p
                          #:rule-processed-p
                          #:query-inactive-p
                          #:query-processed-p
                          #:active-expensive-rule-p
                          #:active-expensive-query-p
                          #:cheap-rule-p
                          #:cheap-query-p
                          #:rule-active-p
                          #:query-active-p
                          #:rule-waiting-p
                          #:query-waiting-p
                          #:execute-applicable-rules
                          #:unapplicable-rules
                          #:applicable-rules
                          #:add-chosen-sets-of-rule-consequences
                          #:choose-current-set-of-rule-consequences
                          #:rule-applicable-p
                          #:rule-prepared-p
                          #:query-prepared-p
                          #:reexecute-rule
                          #:reexecute-query
                          #:reprepare-rule
                          #:reprepare-query
                          #:execute-rule
                          #:execute-query
                          #:rule-ready-p
                          #:query-ready-p
                          #:next-set-of-rule-consequences-available-p
                          #:next-tuple-available-p
                          #:get-current-set-of-rule-consequences
                          #:get-next-set-of-rule-consequences
                          #:get-current-tuple
                          #:get-next-tuple
                          #:delete-rule
                          #:delete-query
                          #:del-rcc-edge
                          #:del-rcc-node
                          #:rcc-edge-label
                          #:rcc-node-label
                          #:rcc-edge
                          #:rcc-node
                          #:rcc-related
                          #:rcc-instance
                          #:rcc-consistent?
                          #:in-rcc-box
                          #:in-mirror-data-box
                          #:description-implies?
                          #:edge-label
                          #:node-label
                          #:del-data-edge
                          #:del-data-node
                          #:data-edge
                          #:data-node
                          #:in-data-box
                          #:undefquery
                          #:def-and-exec-query
                          #:def-and-prep-query
                          #:defquery
                          #:preprule
                          #:firerule
                          #:prepare-abox-rule
                          #:prepare-tbox-query
                          #:prepare-abox-query
                          #:apply-abox-rule
                          #:tbox-retrieve1
                          #:tbox-retrieve
                          #:retrieve-under-premise
                          #:retrieve1
                          #:retrieve
                          #:with-nrql-settings
))

(defconstant +nrql-symbols+ '(
                          #:with-nrql-standard-settings
                          #:racer-retrieve-individual-filled-roles
                          #:racer-retrieve-individual-fillers
                          #:racer-retrieve-related-individuals
                          #:xml-output
                          #:xml-input
                          #:lisp-to-xml
                          #:xml-to-lisp
                          #:nrql-equal-role
                          #:all-types
                          #:types
                          #:instantiators
                          #:all-instantiators
                          #:all-types-flat
                          #:all-instantiators-flat
                          #:types-flat
                          #:instantiators-flat
                          #:direct-types
                          #:most-specific-types
                          #:most-specific-instantiators
                          #:direct-instantiators
                          #:direct-types-flat
                          #:most-specific-types-flat
                          #:most-specific-instantiators-flat
                          #:direct-instantiators-flat
                          #:describe
                          #:individual-synonyms
                          #:bind-individual
                          #:inv
                          #:not
                          #:neg
                          #:and
                          #:or
                          #:satisfies
                          #:top
                          #:bottom
                          #:true-query
                          #:false-query
                          #:constraint
                          #:has-known-successor
                          #:substitute
                          #:insert
                          #:same-as
                          #:equal
                          #:=
                          #:intersection
                          #:union
                          #:cap
                          #:cup
                          #:lambda
                          #:told-value
                          #:told-values
                          #:told-value-if-exists
                          #:told-values-if-exists
                          #:datatype-filler
                          #:datatype-fillers
                          #:annotation-datatype-filler
                          #:annotation-datatype-fillers
                          #:unknown-operator
                          #:bindings-from
                          #:no-told-value
                          #:no-known-cd-objects
                          #:project
                          #:project-to
                          #:pi
                          #:real-top
                          #:real-bottom
                          #:store-substrate-for-current-abox
                          #:restore-all-substrates
                          #:restore-substrate
                          #:store-all-substrates
                          #:store-substrate-for-abox
                          #:get-nrql-version
                          #:del-rcc-edge1
                          #:del-rcc-node1
                          #:rcc-edge-label1
                          #:rcc-node-label1
                          #:rcc-edge1
                          #:rcc-node1
                          #:rcc-related1
                          #:rcc-instance1
                          #:rcc-consistent-p
                          #:create-rcc-edge
                          #:create-rcc-node
                          #:set-rcc-box
                          #:set-mirror-data-box
                          #:description-implies-p
                          #:set-data-box
                          #:get-data-edge-label
                          #:get-data-node-label
                          #:delete-data-edge
                          #:delete-data-node
                          #:create-data-edge
                          #:create-data-node
                          #:get-substrate-edge-assertions
                          #:get-substrate-edges
                          #:get-substrate-node-assertions
                          #:get-substrate-nodes
                          #:get-process-pool-size
                          #:get-maximum-size-of-process-pool
                          #:get-initial-size-of-process-pool
                          #:set-maximum-size-of-process-pool
                          #:set-initial-size-of-process-pool
                          #:set-rewrite-defined-concepts
                          #:set-nrql-mode
                          #:show-current-qbox
                          #:get-abox-of-current-qbox
                          #:disable-query-realization
                          #:enable-query-realization
                          #:optimizer-dont-use-cardinality-heuristics
                          #:optimizer-use-cardinality-heuristics
                          #:disable-query-optimization
                          #:enable-query-optimization
                          #:disable-query-repository
                          #:enable-query-repository
                          #:dont-report-tautological-queries
                          #:report-tautological-queries
                          #:dont-report-inconsistent-queries
                          #:report-inconsistent-queries
                          #:describe-query-processing-mode
                          #:describe-current-substrate
                          #:include-permutations
                          #:exclude-permutations
                          #:dont-add-rule-consequences-automatically
                          #:add-rule-consequences-automatically
                          #:process-set-at-a-time
                          #:process-tuple-at-a-time
                          #:get-max-no-of-tuples-bound
                          #:set-max-no-of-tuples-bound
                          #:dont-check-abox-consistency-before-querying
                          #:check-abox-consistency-before-querying
                          #:enable-lazy-tuple-computation
                          #:enable-eager-tuple-computation
                          #:restore-standard-settings
                          #:dont-add-role-assertions-for-datatype-properties
                          #:add-role-assertions-for-datatype-properties
                          #:disable-told-information-querying
                          #:enable-told-information-querying
                          #:disable-nrql-warnings
                          #:enable-nrql-warnings
                          #:disable-kb-has-changed-warning-tokens
                          #:enable-kb-has-changed-warning-tokens
                          #:disable-phase-two-starts-warning-tokens
                          #:enable-phase-two-starts-warning-tokens
                          #:disable-two-phase-query-processing-mode
                          #:enable-two-phase-query-processing-mode
                          #:disable-abox-mirroring
                          #:enable-very-smart-abox-mirroring
                          #:enable-smart-abox-mirroring
                          #:enable-abox-mirroring
                          #:disable-sql-data-substrate-mirroring
                          #:enable-sql-data-substrate-mirroring
                          #:use-$?-prefix-for-una-variables
                          #:use-?-prefix-for-una-variables
                          #:dont-use-individual-synonym-equivalence-classes
                          #:use-individual-synonym-equivalence-classes
                          #:disable-data-substrate-mirroring
                          #:enable-data-substrate-mirroring
                          #:wait-for-rules-to-terminate
                          #:wait-for-queries-to-terminate
                          #:describe-all-rules
                          #:describe-all-queries
                          #:get-all-answers
                          #:get-answer-size
                          #:run-all-rules
                          #:reexecute-all-rules
                          #:execute-all-rules
                          #:run-all-queries
                          #:reexecute-all-queries
                          #:execute-all-queries
                          #:abort-all-rules
                          #:abort-all-queries
                          #:terminated-rules
                          #:inactive-rules
                          #:processed-rules
                          #:terminated-queries
                          #:inactive-queries
                          #:processed-queries
                          #:waiting-expensive-rules
                          #:waiting-cheap-rules
                          #:waiting-rules
                          #:waiting-expensive-queries
                          #:waiting-cheap-queries
                          #:waiting-queries
                          #:running-expensive-rules
                          #:running-cheap-rules
                          #:running-rules
                          #:running-expensive-queries
                          #:running-cheap-queries
                          #:running-queries
                          #:active-expensive-rules
                          #:active-cheap-rules
                          #:active-rules
                          #:active-expensive-queries
                          #:active-cheap-queries
                          #:active-queries
                          #:prepared-rules
                          #:ready-rules
                          #:prepared-queries
                          #:ready-queries
                          #:expensive-rules
                          #:cheap-rules
                          #:inaccurate-rules
                          #:accurate-rules
                          #:all-rules
                          #:expensive-queries
                          #:cheap-queries
                          #:inaccurate-queries
                          #:accurate-queries
                          #:all-queries
                          #:describe-all-definitions
                          #:describe-definition
                          #:delete-all-definitions
                          #:undefine-query
                          #:define-and-prepare-query
                          #:define-and-execute-query
                          #:define-query
                          #:racer-prepare-tbox-query
                          #:racer-answer-tbox-query1
                          #:racer-answer-tbox-query
                          #:racer-prepare-rule
                          #:racer-apply-rule
                          #:prepare-nrql-engine
                          #:racer-prepare-query
                          #:racer-answer-query-under-premise
                          #:racer-answer-query1
                          #:racer-answer-query
                          #:full-reset
                          #:reset-nrql-engine
                          #:reset-all-substrates
                          #:delete-all-rules
                          #:delete-all-queries
                          #:describe-rule
                          #:describe-query
                          #:get-dag-of-qbox-for-abox
                          #:show-qbox-for-abox
                          #:get-nodes-in-qbox-for-abox
                          #:get-nodes-in-current-qbox
                          #:get-dag-of-current-qbox
                          #:query-equivalents
                          #:query-descendants
                          #:query-children
                          #:query-ancestors
                          #:query-parents
                          #:query-equivalent-p
                          #:query-entails-p
                          #:classify-query
                          #:query-tautological-p
                          #:query-inconsistent-p
                          #:query-consistent-p
                          #:abort-rule
                          #:abort-query
                          #:original-rule-body
                          #:original-query-body
                          #:rule-body
                          #:query-body
                          #:original-rule-head
                          #:original-query-head
                          #:rule-head
                          #:query-head
                          #:rule-accurate-p
                          #:query-accurate-p
                          #:get-answer
                          #:get-all-remaining-sets-of-rule-consequences
                          #:get-all-remaining-tuples
                          #:get-next-n-remaining-sets-of-rule-consequences
                          #:get-next-n-remaining-tuples
                          #:describe-rule-status
                          #:describe-query-status
                          #:rule-inactive-p
                          #:rule-processed-p
                          #:query-inactive-p
                          #:query-processed-p
                          #:active-expensive-rule-p
                          #:active-expensive-query-p
                          #:cheap-rule-p
                          #:cheap-query-p
                          #:rule-active-p
                          #:query-active-p
                          #:rule-waiting-p
                          #:query-waiting-p
                          #:execute-applicable-rules
                          #:unapplicable-rules
                          #:applicable-rules
                          #:add-chosen-sets-of-rule-consequences
                          #:choose-current-set-of-rule-consequences
                          #:rule-applicable-p
                          #:rule-prepared-p
                          #:query-prepared-p
                          #:reexecute-rule
                          #:reexecute-query
                          #:reprepare-rule
                          #:reprepare-query
                          #:execute-rule
                          #:execute-query
                          #:rule-ready-p
                          #:query-ready-p
                          #:next-set-of-rule-consequences-available-p
                          #:next-tuple-available-p
                          #:get-current-set-of-rule-consequences
                          #:get-next-set-of-rule-consequences
                          #:get-current-tuple
                          #:get-next-tuple
                          #:delete-rule
                          #:delete-query
                          #:del-rcc-edge
                          #:del-rcc-node
                          #:rcc-edge-label
                          #:rcc-node-label
                          #:rcc-edge
                          #:rcc-node
                          #:rcc-related
                          #:rcc-instance
                          #:rcc-consistent?
                          #:in-rcc-box
                          #:in-mirror-data-box
                          #:description-implies?
                          #:edge-label
                          #:node-label
                          #:del-data-edge
                          #:del-data-node
                          #:data-edge
                          #:data-node
                          #:in-data-box
                          #:undefquery
                          #:def-and-exec-query
                          #:def-and-prep-query
                          #:defquery
                          #:preprule
                          #:firerule
                          #:prepare-abox-rule
                          #:prepare-tbox-query
                          #:prepare-abox-query
                          #:apply-abox-rule
                          #:tbox-retrieve1
                          #:tbox-retrieve
                          #:retrieve-under-premise
                          #:retrieve1
                          #:retrieve
                          #:with-nrql-settings
))

